"""Initial Migration

Revision ID: 31fb4b49bba5
Revises: 
Create Date: 2021-06-14 23:11:40.494598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31fb4b49bba5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('profile_pic_path', sa.String(), nullable=True))
    op.add_column('comments', sa.Column('poster_name', sa.String(length=255), nullable=True))
    op.add_column('comments', sa.Column('uname', sa.String(length=255), nullable=True))
    op.add_column('pitches', sa.Column('profile_pic_path', sa.String(), nullable=True))
    op.add_column('pitches', sa.Column('poster_name', sa.String(length=255), nullable=True))
    op.add_column('pitches', sa.Column('uname', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitches', 'uname')
    op.drop_column('pitches', 'poster_name')
    op.drop_column('pitches', 'profile_pic_path')
    op.drop_column('comments', 'uname')
    op.drop_column('comments', 'poster_name')
    op.drop_column('comments', 'profile_pic_path')
    # ### end Alembic commands ###
