"""Add likes 2

Revision ID: 540e3814066f
Revises: 0a5c0ccb3dec
Create Date: 2021-06-16 12:51:25.593035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '540e3814066f'
down_revision = '0a5c0ccb3dec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitches', 'likes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('likes', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
