"""Update models.

Revision ID: 63ff9c5b4677
Revises: 31fb4b49bba5
Create Date: 2021-06-15 00:16:56.028970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63ff9c5b4677'
down_revision = '31fb4b49bba5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('name', sa.String(length=255), nullable=True))
    op.drop_column('comments', 'profile_pic_path')
    op.drop_column('comments', 'uname')
    op.drop_column('comments', 'poster_name')
    op.drop_column('pitches', 'profile_pic_path')
    op.drop_column('pitches', 'uname')
    op.drop_column('pitches', 'poster_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('poster_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('pitches', sa.Column('uname', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('pitches', sa.Column('profile_pic_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('comments', sa.Column('poster_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('comments', sa.Column('uname', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('comments', sa.Column('profile_pic_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('categories', 'name')
    # ### end Alembic commands ###
