"""Update likes for comments

Revision ID: ac64bf0b8579
Revises: 9561fc7719a8
Create Date: 2021-06-16 13:37:28.162304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac64bf0b8579'
down_revision = '9561fc7719a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment_likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('comment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('comments', 'dislikes')
    op.drop_column('comments', 'likes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('likes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('comments', sa.Column('dislikes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_table('comment_likes')
    # ### end Alembic commands ###
