"""Deployment

Revision ID: bafba0ee1d28
Revises: 4117808904a1
Create Date: 2021-06-15 18:24:06.421234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bafba0ee1d28'
down_revision = '4117808904a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('category', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'category')
    # ### end Alembic commands ###
